### ISSUE TITLE
New Charge BKB upgrade ladder

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#1127]

**Comment by KarmaticNeutral** [comment]
![img_0017](https://user-images.githubusercontent.com/24883381/27013229-0ced5e14-4e9d-11e7-87f1-e3398f517bb0.PNG)

**Comment by Haganeko** [comment]
Attempt to make CBKB laddering work in a sane way. Look at Greaves for an example of how to implement it.

**Comment by Trildar** [comment]
So, BKB1 + UC1 + Wand + Recipe = CBKB1 like it is now. And the sidegrade is BKB(n+1) + Wand + CBKB1 Recipe = CBKB(n)? Or do we want to use CBKB(n) recipe instead?

**Comment by Haganeko** [comment]
Just BKB(n+1) + Wand + Recipe = CBKB(n) 
Well that and CBKB(n) + UC(n+1) = CBKB(n+1)

**Comment by Trildar** [comment]
**Which** recipe? That's what I'm trying to ask. XD
Also, I'm guessing you meant CBKB(n) + UC(n+1) + Recipe = CBKB(n+1)

**Comment by Haganeko** [comment]
Yes on the recipe thing. Well, if you look at Greaves, we made a dummy recipe. It looks like Greaves recipe, it walks like Greaves recipe, but it's actually item_greater_greaves_dummy

**Comment by Trildar** [comment]
I know that, but unlike Greaves, there isn't any way upgrading from BKB can cost the same amount as if you  bought Charge BKB from level 1, so I was just wondering if we still wanted it to sidegrade with level 1 recipe.

**Comment by Haganeko** [comment]
Hm. Currently,  it costs the same on a recipe to upgrade to BKB 2 and CBKB?
Hm. We are buffing the item with the charge thing, so I think making the recipe add up to 1k with the wand would work. Maybe even 1.5

**Comment by Trildar** [comment]
BKB 2 recipe costs 1500. It's the standard recipe cost for all Tier 1 upgrades. I think we so far haven't deviated from that. Except for current CBKB 1 recipe, which is 60, presumably because it wasn't touched way back when we implemented the standard paper recipes for all upgrades.
Assuming CBKB 1 recipe is 1500, the only extra cost it has over BKB 2 is the wand. And even if we increase the CBKB 1 recipe cost, I'm not sure how we could incorporate the difference in cost into the sidegrade recipe.

**Comment by Haganeko** [comment]
I'm saying we should remove the CBKB 1 = BKB 1 + core + Wand + Recipe and only have sidegrades and CBKB -> CBKB upgrades. 
If that seems bad, then just adjust the recipe cost of the upgrade I think we should remove so it costs the same either way.
