### ISSUE TITLE
Clearing cave before duel causing TPing

### ISSUE THREAD

**Issue by Bellwar** [OpenAngelArena/oaa#1146]
Not exactly sure what happened, but my teammates where clearing the cave, the duel started and they got bugged into the cave and just moving around. After duel ended they still were stuck. In the next duel the game tried to move them into duel and they were inside for brief moments and moving across the whole map. I will try to upload video on youtube and post it here when it will be on there.

**Comment by Bellwar** [comment]
The video is little longer, I am sorry Movie Maker didn't allow me to edit the video for some reason. Also, I am not sure if you can actually do something about this. Maybe, do not try move people in cave when there is duel going on.

https://youtu.be/n0Df1ElIx58

**Comment by allanvbhg** [comment]
Did it act like the last phase of charger? Where it 'grabs' people and shoots acros a coupoe of times?

**Comment by allanvbhg** [comment]
But than all over the map?

**Comment by Bellwar** [comment]
No it was like if you change the coordinates and moves the player instantly and all over the map, sorry I meant between duel at right bottom corner and cave on top right and sometimes you could see for really really short time make them appear between this two places. It was basically trying to keep them out of cave (like when you try blink inside part that's still lock) and at the same time put them into duel and the game didn't have priority and was fighting itself teleporting them and they could to away or move.

**Comment by Chronophylos** [comment]
Thanks for the report

**Comment by Athight** [comment]
Not sure if anyone is working on this, but after looking around I made a few observations:

1) at the end of a duel, it looks like units are sent back to where they came from.
- https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/components/duels/duels.lua
line 540 -> line 611 -> line 633

2) since heros ought to be shoved outside the cave, since they are flickering, could be an inbuilt dota issue, or overlapping zone issue? looks like there's potential for an infinite trigger loop here..
- https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/components/zonecontrol/zones.lua
line 68 -> line 82 -> line 236 -> line 337


1 could probably be fixed by an explicit check on the teleport
2 should probably be fixed by checking whether the new point will trigger anything new.


of course i haven't actually tested this (or even pulled the code) ((or even have used lua)), purely observational, so if i'm talking nonsense, please ignore me ^^;;
no idea why a new duel doesn't fix this though..

**Comment by Haganeko** [comment]
Beginning of duel teleports people and blink blockers interfere.

**Comment by warpdragon** [comment]
We need a line like...
If Farming Cave TP Time After Duel Start Time --> No Farming Cave TP

**Comment by Anemolo** [comment]
I someone is working on this: https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/components/cave/cave.lua

In line 321-324 this is trying to be prevented by 'quick teleporting' the units to their respective spawn if the duel is active. Which is thing that starts the bug. But the bug itself might be what @Athight said.
 
To avoid but not solve the bug - which might as well be a inbuilt dota issue -.
The best solution Changing lines 321 - 325 for:
`
self:TeleportAll(units,spawns) -- Letting the teleportation process & animation begin
` 

But also change Lines 349 -355 for:

`if not Duels.currentDuel then -- But Checking right before teleporting
    FindClearSpaceForUnit(
      unit, -- unit
      spawns[unit:GetTeamNumber()], -- location
      false -- ???
    )

    MoveCameraToPlayer(unit)

    unit:stop();

end
`
Checking if the duel is active right before teleporting. Instead of checking before starting the process. Gives the players a sense of accomplishment by giving them a pretty animation. And solves the issue altogether.

**Comment by Chronophylos** [comment]
If you want you can open a PR with that fix. If not I'll include it in my fix branch. (with credits ofc).

**Comment by l34Um1** [comment]
Closed because fixed.
