### ISSUE TITLE
StoneSkin nerf needed

### ISSUE THREAD

**Issue by prsnnami** [OpenAngelArena/oaa#1218]
I playing a clinks with a lvl5 deso and a lvl 5 solar crest and my team mate with a weaver with lvl5 deso(doesnot matter tho) and the creep swarm dealt almost no damage as soon as the enemy bought the stoneskin, like a lvl5 crest , lvl5 deso and the swarm on him and he was still taking only 10% (i think) of the damage we dealt to him a minute ago. I mean 130 armor is so much.

**Comment by prsnnami** [comment]
this is also possibly the reason why the cheap armlet existed, cause no one will think or buying the armlet over this.

**Comment by Haganeko** [comment]
Armlet was just a copypasta mistake. It happens when inputting data en masse.
As for Stoneskin, the total reduced armor from the effects you mentioned is 110 minus armor, which almost completely negates the item. It may be a problem anyways, But if they were taking only 10% of the damage, they must have had another 130 armor from somewhere (90% damage reduction).

**Comment by warpdragon** [comment]
Considering Baumi did this two weeks ago:
* Stoneskin
Significantly reduced Stoneskins cost, it should be a viable option now.

I'm guessing it didn't need a nerf afterall.
Closed.
