### ISSUE TITLE
Fountain Target Range too long

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#129]
Fountain targets units too far from spawn. You can abuse this to xp farm the first camp. And it seems like the range shouldn't attack anything that isn't on the fountain's high ground.

**Comment by Declow0** [comment]
Even with 300 attack range creeps can die.
https://steamuserimages-a.akamaihd.net/ugc/82594996598984544/406865EA307BC2768BB24223AAAD4F1712653F68/
I think the bottom hill must be longer.

**Comment by Chronophylos** [comment]
The problem are the creeps following the player too long. Their range should get decrease too.

**Comment by MNI-MorganFreefarm** [comment]
There are 2 points of seeing this problem:
First of all, the attack range should keep enemy heroes away, but on the other hand you should not be able to abuse it to farm (as you already mentioned).
I personally think that there are 2 possible ways to handle this issue.

Decreasing the attack range to for example 250 (Svens range with stormhammer to illustrate the radius) is maybe reasonable for the creeps but can probably cause problems with enemy heroes abusing the short range.

![20170322214528_1](https://cloud.githubusercontent.com/assets/26609791/24220091/5366b8b0-0f49-11e7-9ca9-fbf639010b19.jpg)

The second option i see here is maybe favorable, which would include a modify of the map.
With moving the fountain round about 300 to 400 units away of the creeps, you can make sure you dont abuse the range + you could increase the fountain range to have more space between enemy heroes and teammates.

I know that there will be another creep camp for "safe farming".
For this problem you could maybe just move the camp a bit further (should be possible, because behind the fountains there is no space problem), or what i would not appreciate, get rid of this first camp.

**Comment by Honeth** [comment]
first of the default range of fountain is 1200 i already nerfed it by 400 to hope to make the pulling less. which is why it's 800 atm. were probably going to fix it further by making the fountain ignore 'DOTA_TEAM_NEUTRALS` so yeah farming creeps with fountain will probably not last for another 1-2 weeks

**Comment by Haganeko** [comment]
If the fountain will ignore neutrals, maybe increasing its range back will be good to prevent easy sniper camping.

**Comment by KarmaticNeutral** [comment]
I would vote for leaving it at 800 MAYBE increasing to 1000 but at 1200 it would kill players trying to steal the other teams farm that accidentally got too close to fountain.

If we do move it back out it would be best to put in something to visibly show how far out the fountain shoots.

**Comment by Honeth** [comment]
Keep in mind that there's paths above and below fountain to allow enemy team to sneak past and get into their enemies farming caves if we change the range up people won't be able to walk there (although this 800 is prob even too big for that)

**Comment by MNI-MorganFreefarm** [comment]
Keeping in mind that the radius of Svens Q is about 255 and is close to this path...how will you make it possible for enemies to get through it?

Will they need special items/skills for not getting destroyed by the fountain?

**Comment by Chronophylos** [comment]
I like this
* Players only get damaged by creeps in their fountain
* Players get wrecked by the enemy fountain
* Creeps get ignored by the fountain
* Creeps will not follow the player to the fountain

**Comment by Haganeko** [comment]
Is this fixed?

**Comment by Chronophylos** [comment]
Partially. The real problem is the long leash of the creeps.
