### ISSUE TITLE
Multiple item issues

### ISSUE THREAD

**Issue by CruelGod** [OpenAngelArena/oaa#130]
#### Issues about Upgradable Dota items:
* [ ] Desolator and Blightstone Upgrades don't apply the debuff
* [ ] Manta Style Level 4 spawns 2 Illusions
* [x] There isn't a 3rd level of Armlet even tho it shows 3 tiers of stats in the tooltip

#### Weird Issues about AAA items:
* [x] Shiva's Rush level 1 and 2 is not craftable no matter what you do
* [x] Lvl 1 Greater Power Treads cleave but lvl 2,3 and 4 does not cleave
* [ ] Lvl 1 and 2 Eul's Scepter of Sancticity have the exact same stats (tested out by comparing stats ingame)

Random fact: The level cap is 5000

Edit by @Chronophylos: Markdown

**Comment by CruelGod** [comment]
Also fun fact: The level cap is 5000

**Comment by Chronophylos** [comment]
The LvlCap is at 5000 for a reason.
1. It's not important at that point in the game anymore.
2. We generate a table with an `needed total xp` value for this for every single entry. If we choose a LvlCap of 6300+ the game crashes. I suspect this happens because the generated table is too big for DotA to send to the clients.

**Comment by warpdragon** [comment]
cleave is fixed on my fork. shivas rush should be fixed too. recipe had some garbage in it.

**Comment by Haganeko** [comment]
How much of this is done?

**Comment by chrisinajar** [comment]
I'm going to close this in favor of granular tickets
