### ISSUE TITLE
Duel code calls GetAbilityByIndex with invalid index

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#135]
In the `Duels:ResetPlayerState` function and elsewhere, there are loops going from 0 to `hero:GetAbilityCount()`. I'm guessing that it should actually be `hero:GetAbilityCount() - 1` since abilities are zero-indexed?

**Comment by chrisinajar** [comment]
If they're zero indexed then the code also isn't resetting the cd of the 0th slot ability (admittedly, i only tested with  hero that has an attack modifier in that slot, haha)

Whoever tackles this, please check if items have their CD's reset as well, and if not then fix that.

**Comment by Trildar** [comment]
Do the loops not start at 0? Or did you mean `GetAbilityByIndex(0)` returns nil? If it's the latter then I'm probably just mistaken in assuming it's zero-indexed.

**Comment by chrisinajar** [comment]
yeah it starts with 0, it just needs to be -1.

zero indexed indeed.

**Comment by RamonNZ** [comment]
After testing I can say that it is 0 indexed. For example if you start the index at -1 then you get two error messages instead of one. 

What's happening is that hero:GetAbilityCount() is returning 24 abilities (go figure) , so the For statement  starts at 0 then goes to 24, so actually runs 25 times. The valid numbers are 0-23. The fix is hero:GetAbilityCount()-1.
