### ISSUE TITLE
Infinite death

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#146]
During duels we disable respawning. For some reason sometimes you die forever even though we re-enable respawn at the end of the duel. Dying forever kind of sucks, so please fix.

**Comment by spar36** [comment]
Question. Why do you re-enable respawn in two locations in the same function?
Lines 255 and 268 of duels.lua

And why do you instantly respawn the units on line 269, but don't on 256

**Comment by chrisinajar** [comment]
it was an attempt to fix the bug, players respawn from the duel fine

**Comment by RamonNZ** [comment]
The above fix has been tested single player, then multi-player with bots. All respawning is working.

**Comment by RamonNZ** [comment]
Hi chrisinajar:

regarding:
"  -- why dont these run?" in duels.lua

The answer is that all of your code fired, and units still didn't respawn regardless.

[VScript] [components\duels\duels:253]	Duel has ended
[VScript] [components\duels\duels:277]	Is this a player id? 5
[VScript] [components\duels\duels:277]	Is this a player id? 6
[VScript] [components\duels\duels:277]	Is this a player id? 7
[VScript] [components\duels\duels:277]	Is this a player id? 8
[VScript] [components\duels\duels:277]	Is this a player id? 9
[VScript] [components\duels\duels:277]	Is this a player id? 0
[VScript] [components\duels\duels:277]	Is this a player id? 1
[VScript] [components\duels\duels:277]	Is this a player id? 2
[VScript] [components\duels\duels:277]	Is this a player id? 3
[VScript] [components\duels\duels:277]	Is this a player id? 4

Progress: Units who die before the duel starts get permadeath. They actually respawn during the duel if they die again or if their first respawn timer hits 0, then after the duel ends they get permadeath.

**Comment by RamonNZ** [comment]
Problem #1: If they die before the duel starts, and have a respawn timer counting down, the timer will still cause a respawn during the duel, whether they're dead or alive. Then if you die during the duel you'll respawn again. Then...

Problem #2: Permadeath happens partly because you save the state of a dead unit, then respawn the unit, then restore it's state (0 HP/dead) with RestorePlayerState, which kills it, but perhaps its respawn timer is 0/-1.

Problem #3: Minor - when you respawn after a duel you respawn where you died instead of at your fountain, meaning possibly right in the middle of creeps or enemy heroes.

Solutions #1: hero:SetTimeUntilRespawn(-1) after the instances of 
                    hero:RespawnUnit()
Notes: -1 doesn't seem to cause a problem, 0 does cause a problem, and causes every unit to respawn whether they're dead or not. This kills the respawn timer.

Solutions #2: This one is simple thankfully:
      Duels:ResetPlayerState(player:GetAssignedHero()) - ie respawn all dead heroes before you:
      Duels:SavePlayerState(player:GetAssignedHero())

Solutions #3: This one doesn't urgently need addressing.

I have a working duels.lua presently, I'm just hoping to catch any bugs before I make the changes.

**Comment by KarmaticNeutral** [comment]
It looked from hours of testing today that perma death got fixed. I am 95% confident this is true. I could still be wrong though.

**Comment by RamonNZ** [comment]
Oh... maybe I have an older version. Thanks for lmk.

**Comment by KarmaticNeutral** [comment]
I don't think the fix was intentional. Chris changed something with the way people spawn in duels and now people often spawn in twice. It could have been an accidental fix with that. I don't know. I just know that after a specific patch earlier I never saw a perma dead player again.

**Comment by RamonNZ** [comment]
It was intentional trust me. An inelegant solution is better than a game breaking bug.
