### ISSUE TITLE
Make Lucience heal instead of regen

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#1517]
Currently Lucience is overpowered because of the interactions with strength. Instead of adding regen, it should just heal on a time interval (configured from KV)

**Comment by l34Um1** [comment]
Healing on a 0.1 interval. Basically exactly WD heal.

**Comment by Haganeko** [comment]
Can't we just nerf the numbers? It'd be a way more natural fix. I mean, how many heal over time effects are left in Dota by now? WD and Oracle heals.

**Comment by l34Um1** [comment]
It's because of the new regen mechanics. There is no way to properly balance Lucience without this change.

With the current numbers I have seen lvl 1 Lucience regen vary from 100-400. It's dumb.

**Comment by Haganeko** [comment]
I assume that's either a bug or an exaggeration, since people would need to have between 77 and 730 strength to obverse those values.
In any case, you'll see similar situations with Urn heal, Wyvern heal, and anything else. What needs to be done is reducing the availability of strength like we did agility, lowering the values on Lucience, and finding out if there's some bug that lets people have over 700 strength early.

**Comment by l34Um1** [comment]
And how is any of that less work than just fixing the one problem item? Especially since all of it's numbers are in a fine state of balance. Also keep in mind that people usually carry more than one item that gives regen, making the numbers higher.

**Comment by Haganeko** [comment]
If people have more items, those will still be affected by the multipliers and this will not solve the problem.
The numbers were in a fine state of balance prior to the changes. But the way to adapt to changes in the game is not to attempt to undo them, it's to make our stuff work. At least if we want to stay close to vanilla.
I didn't say this was the easiest way to fix it. It is, however, the most natural and effective way.

**Comment by l34Um1** [comment]
No it's not. The whole point of Lucience is to be a constant source of strong reliable healing. Your suggestion makes the healing either go insane on tanks or useless on everybody else. Lucience needs naturally higher numbers than anything else. We can balance every other item the way you said and that's how I plan on doing it. But Lucience is an exception because healing with regen is the only thing it does. It's numbers are higher. This change will make all of our lives easier for the future.

**Comment by Haganeko** [comment]
Okay, then. Do recall that tanks have a higher HP pool, and that this item will then instead become unintuitive for new players, who will expect strength to affect all heal over time - especially if Valve keeps going with the tendency and reworks WD to use regen.
Well, at least oracle will likely stay as is.

**Comment by l34Um1** [comment]
Rephrase "regeneration" to "Heals X HP per second". Then it's clear.

**Comment by SquawkyArctangent** [comment]
Witch Doctor heal doesn't heal in 10-per-second intervals; it heals in 3-per-second. Oracle heals are 1-per-second.

**Comment by SquawkyArctangent** [comment]
#1524

**Comment by l34Um1** [comment]
Implemented.
