### ISSUE TITLE
New items and old Reflex items require proper tooltips

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1678]
Pure KV busy work. Include all stats in the tooltip. Make them adjust with the KV files. 

Item builds out of | Old Reflex Item
--------------------|-------------------
Heart 2 | Regeneration Crystal
BKB 2 | Enrage Crystal
Lotus Orb 3 | Bubble Orb
Linkens 2 | Reflection Shard
Crimson Guard 2 | Reduction Orb
Lotus Orb 2 | Dispel Orb

Add an orange colored text to the tooltips for transformation items: "This is a Transformation item. You may only one of these active at once." Or something to that extent.

**Comment by imaGecko** [comment]
Might as well include renaming the internal name and redoing the folders since they are normal items now instead of reflex items. 

Regen Crystal is already done with #1679

**Comment by Trildar** [comment]
The Transformation items should have a note already, but it's only in the alt+hover text, mainly to take advantage of the fancy new tooltip referencing system I think. I do think that it might warrant moving into the normal description though.

@chrisinajar Does the tooltip system support splicing text?

**Comment by chrisinajar** [comment]
`"asdfasdf #{some_other_thing} fdsa asdf fdsa #{another_tooltip_why_not}"`

The test cases cover multiply nested and crazy things like nesting a tooltip nested in another tooltip you also nested. It should all work.

It'd be good to also make a generic tooltip with the color tag for the item titles (since transformation items should have a special color). That'd let us change the color globally at any time.

The translation system is unaware of the tokens, so there's no advantage there for using them. They're purely for maintaining the tooltips (which then get translated as needed)

**Comment by imaGecko** [comment]
#1733 #1734
