### ISSUE TITLE
Bkb doesnt purge.

### ISSUE THREAD

**Issue by Melongod** [OpenAngelArena/oaa#1758]
bkb doesnt purge anything at all.

**Comment by Melongod** [comment]
basic dispel

**Comment by imaGecko** [comment]
#1775

**Comment by ThatMusicWriter** [comment]
I have the code written out, but because I'm new to this, I do not know how to get it to you guys. However, someone who does can just copy/paste this after the "function item_black_king_bar_1:OnSpellStart()" line:


function item_black_king_bar_1:OnSpellStart()
	local caster = self:GetCaster()

	caster:AddNewModifier( caster, self, "modifier_black_king_bar_immune", {
		duration = self:GetSpecialValueFor( "duration" ),
	} )

	  -- void Purge(bool bRemovePositiveBuffs, bool bRemoveDebuffs, bool bFrameOnly, bool bRemoveStuns, bool bRemoveExceptions)
  	caster:Purge(false, true, false, true, true)

	caster:EmitSound( "DOTA_Item.BlackKingBar.Activate" )

	-- wow bkb is a basic item without the decay
end

**Comment by Haganeko** [comment]
As ImaGecko has noted, I believe this is done.

**Comment by ThatMusicWriter** [comment]
Well, it's still listed as being open, so I thought I'd help, but thanks for letting me know.
