### ISSUE TITLE
Make Bosses break Heart regeneration

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1834]

**Comment by Haganeko** [comment]
Hallelujah, brothers and sisters! 🙌

**Comment by Melongod** [comment]
Too big of a change to have before the tournament.
All for this, but after the tournament.

**Comment by Melongod** [comment]
We really cant have big changes on the flow of the game before the tournament.

**Comment by warpdragon** [comment]
it's not really that big. it's just a nerf to heart. nobody buys heart, melon. nobody.

**Comment by chrisinajar** [comment]
Why change this? It's the only thing that makes heart good, this change might as well just remove the item and replace it with regen crystal. Heart is literally only good because bosses don't break it, and even then I argue regen crystal is better... This change centralizes item selection... 

We need to find a solution that keeps heart viable, we shouldn't be in the business of nerfing already garbage items.

**Comment by imaGecko** [comment]
Regen Crystal is better. Provides the same amount of HP, more of it coming from strength, and active regen that can be used at any point only excluding mute and hex while heart only heals out of combat.

**Comment by Haganeko** [comment]
The fact that Regen Crystal is better doesn't mean we shouldn't fix this bug. And it is a bug, because Heart is not meant to provide regen in fights. Bosses are not treated as creeps for anything else, so why this?
If Crystal is too much better than Heart, then increase the stats on Heart and/or decrease the stats on Crystal.

**Comment by Haganeko** [comment]
Is this in, or did you just postpone it?

**Comment by l34Um1** [comment]
tabled for now until after tournament. I do think it's too big of a change to make atm.

**Comment by Haganeko** [comment]
Also back in the menu.

**Comment by Haganeko** [comment]
Additionally, increase Heart Regen back to vanilla values.
