### ISSUE TITLE
Implement Safe to Leave mechanics

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1903]
After the players of a team have been collectively disconnected for some time (suggestion: ten minutes) send the mmr statistics as that team having lost, and any players disconnected at that time as having abandoned.
Show a message on screen alerting players to this.

**Comment by l34Um1** [comment]
If all members of a team leave the game automatically gives a victory to the other team after 90s. 

I assume this is about situations where not everybody disconnected? If so what's the threshold?

**Comment by Haganeko** [comment]
It would be left as configurable, but discussion had reached the value of ten total minutes when summimg the players.

**Comment by KarmaticNeutral** [comment]
Would it be possible to 
1) assess the disconnected players as having lost
2) make the game not count for their teammate since it’s not fair they lose since they did nothing wrong but you also can’t make them win cause that’s abuseable
3) make the other team win?

Mostly I’m concerned about #2 cause disconnects are common and I’m worried that losing games because of disconnects will frustrate people and they just stop playing

**Comment by l34Um1** [comment]
4. What if we make quitting have you lose twice the MMR

**Comment by Haganeko** [comment]
Number two will make it so having one teammate disconnect when losing is an efficient tactic.

**Comment by arrowpack** [comment]
For nr 4, i think only the first player that left should lose twise the mmr.

**Comment by Haganeko** [comment]
The first one, or the one who left for the longest? What if one player DC's by accident, comes back, and all their team just quit?

**Comment by KarmaticNeutral** [comment]
While that’s true haga, I just don’t want people who aren’t responsible for the issue to be punished.

Arrow pack, that’s why there’s a timer and the safe to leave thing. If you want till they’ve abandoned or whatever then you can leave with extra penalty.

**Comment by arrowpack** [comment]
I wouldnt really blame that team, neither would i punish the leaver. Maybe make like a 5 min cap, where if it takes longer than that, the first leaver loses 2x mmr. If someone leaves in those 5 min he is the one losing 2x mmr. Kinda like vanilla dota

**Comment by Haganeko** [comment]
Well, you lose a game of oaa as a team. You don't get to not lose mmr if your teammate played badly or even fed.
As I said, report the people who are DC'd at the end as abandons, and do whatever we do with those

**Comment by KarmaticNeutral** [comment]
That's true, But what about the instance where your team is winning and someone on your team disconnects? You now get evaluated as having lost because they rage quit or have bad internet or whatever it is? It's not your fault.

I don't care how it's done, but if we punish people who did nothing wrong, our player base will shrink. We don't have to use my solution, but we can't just make everyone lose because one person disconnects.

**Comment by Haganeko** [comment]
If someone on your team leaves for ten minutes and you didn't manage to win in that time, what's the chance you were going to win after this? Not very large, one would assume. And if you were much more skilled than your teammates, the mmr system already protects you.

**Comment by Chogex** [comment]
Could there be a way to connect how the game was going to when the player left? So that if the team with the dc was winning by a significant margin the others wouldn't lose mmr if they lose the game, but if the game was even or if they were already losing it'd still count as a loss for them.

**Comment by Haganeko** [comment]
Very hard to measure that. And, again, if your teammate, instead of leaving, started feeding or started playing half heartedly or decided to try a wonky build or first picked a hero that's easily countered, you still lose.

**Comment by Chogex** [comment]
Networth / xp lead + score, both of which would need to be X ahead of the enemy team (significant lead). Obviously there'd be ways to abuse that, but you'd have to know that the game was lost while you're ahead. It's almost impossible to implement a "safe to leave" system that can't be abused.

**Comment by Haganeko** [comment]
How is it not? You leave with this system, and your team has ten minutes to win. If they do, you alone get an abandon. If they don't, you alone get an abandon, and they get a loss.
If you allow people to win, then it's abusable. They can go in as five, get an advantage and have one of them quit to get a quick win.

**Comment by Chogex** [comment]
I didn't mean that they'd win. No mmr change was the point. But I don't understand the 10 minutes of time to win. Punish the rest of the team after one of their teammates dcs? Or is the purpose to make 1v5 endless games impossible.

**Comment by Haganeko** [comment]
That's the idea. The idea is that once a team has left for too long, the game is over, everyone can leave now.
The idea is that if a game has gone on for enough time with less players (say, one team having collectively disconnected for over X minutes), then it's most likely over.
I suggested X = 10, but that can be adjusted.

**Comment by Chogex** [comment]
In that case I think the timer should lower each time a plater leaves. So  that the first one sets the timer to win to X minutes (relatively high e.g. 30 mins). Then each time a player leaves the timer goes down by Y minutes. Because 4v5 games are still relatively winnable and enjoyable.

**Comment by Haganeko** [comment]
Since it's collective leave time, then with two players out it counts twice as fast. Did no one read the post before posting here?

**Comment by Chogex** [comment]
I did not haga, but I'm in too deep to stop now. That sounds fine then other than 10 minutes being way too short for the starting value. Probably should be 30 or 40.

**Comment by KarmaticNeutral** [comment]
I'm really having a problem with the idea that if I queue into a pub match and my team dcs I lose MMR. It wouldn't be my fault. Why should I be penalized. I'm fine with it counting as a win for my opponents still. I'm fine with the timers and I'm fine with my teammates who disconnected losing extra MMR. That all makes sense to me. 

Me losing MMR because my teammate DCed will just cause trolls who don't care about their MMR to enter lobbys and immediately disconnect to screw over their would be teammates.

**Comment by Chogex** [comment]
You could make it so that the remaining players lose less mmr. 2/3 or half of the usual value.

**Comment by KarmaticNeutral** [comment]
While that's better, it doesn't fix the problem. It just makes it hurt less.

**Comment by Haganeko** [comment]
So Karmatic what if they don't DC but just feed a bunch? What if they afk? What then? It's still ruining games.

**Comment by KarmaticNeutral** [comment]
That's true and we should have a different solution to deal with them.

**Comment by KarmaticNeutral** [comment]
I don't see how a different, albeit similar, problem being present means we need to hurt people who did nothing wrong.

**Comment by Haganeko** [comment]
It demonstrates that you lose or win as a team. The person who leaves does get treated more harshly, but what happened is you lost.
I'd love to be able to low prio leavers and have reporting systems, but we don't.

**Comment by KarmaticNeutral** [comment]
That is a great sentiment when people queue into a game with a 5 stack, but with this system in place, I will be in a match for long enough for people to pick heroes then people will DC then I will lose MMR. How is that me losing as a team?

I agree that would be nice to have. We don't have it. Let's not settle for a flawed system just because we can't have our preferred method.

**Comment by chrisinajar** [comment]
You can already deadlock games to prevent losing MMR, this isn't a new exploit.

 * Once the threshold is hit, anyone disconnected loses MMR as if they lost and anyone still connected cannot lose MMR regardless of the game outcome.
 * Whoever (connected players) wins the game should still get MMR as normal, even if it's the team which had disconnects

This makes it so that a game becomes "safe to leave" once the threshold is met, but you can still fight it out if you think it's close or you think you can win the MMR.

**Comment by Haganeko** [comment]
Chris, that stimulates players to hide in the cave to durdle the other team into leaving instead.
Karmatic, this doesn't happen instantly. Your team needs to leave for a WHILE before this happens. If someone disconnects at game start, there's (if we go with Cho's number) half an hour till it happens.

**Comment by Haganeko** [comment]
We want to tell players who are in a 1v5 that it's okay to scoop their cards and leave so everyone can queue again.

**Comment by chrisinajar** [comment]
yeah if they hide in the cave, *just leave*. It's safe to leave, the point. We're not handing out free victories or trying to derive who would have won, we're trying to get everyone to leave the dead game and join a real one.

**Comment by KarmaticNeutral** [comment]
If you hurt players that did nothing wrong they won't queue again. 

If your goal is to get the 1 in the 1v5 to queue again then make it so they don't lose MMR after the threshold and they will DC to queue again.

**Comment by Haganeko** [comment]
Thing is they have lost a game. The same way they can lose a game if they are in a game with four players much worse than them.
People who leave frequently will get more mmr penalties, their mmr will fall into a pit and losing with them on the team will mean little.

**Comment by KarmaticNeutral** [comment]
Haga, is your goal to end dead games and get people to queue into new games?

**Comment by Haganeko** [comment]
My goal is to incentivize people in dead games to leave.
It is not to introduce a mechanic whereby a five stack may save mmr by having one sacrificial lamb leave.

**Comment by chrisinajar** [comment]
You can already do exploits like that. This isn't a new form of abuse.

**Comment by KarmaticNeutral** [comment]
Ok there's the problem.

Your first goal in everything you do on this project should be to get people to enter lobbies. If you don't have a player base you don't have a game.

Your solution very aggressively and completely ends dead games. It also leaves players frustrated and belittled making them not want to return.

**Comment by chrisinajar** [comment]
Haga, can you describe exactly how you want it to work? Most of your posts are disagreeing rather than asserting, so it's hard to tell what it is that you want (other than a reporting system for leavers which is impossible)... Is it just that you want people on the team of the leaver to also lose MMR, and other than that it's the same as what i described?

**Comment by Haganeko** [comment]
Again, you almost never lose a game because you did something wrong. It's because your team lost. If having players not feel entirely responsible for their loss is a problem, we don't want a team game. That player who feels like you described? They're the ones who flame others when they play a little bad, and they might also leave our queues over that.
What we could do is also have a min duration. If the abandon happens before some threshold is reached, no stats are recorded and no one wins or loses anything (except for the person who left, who gets an abandon). Dota uses first blood for that.

**Comment by Haganeko** [comment]
@chrisinajar what I want is what's in the first post.
Count the total time a team has spent disconnected (sum for each player)
When that reaches a limit, the game is over as far as stats are concerned. The team who reached the threshold loses, the other wins, and anyone who's disconnected at that point is issued an abandon.

**Comment by Haganeko** [comment]
I wasn't describing what I wanted because I already had. No one had read it before commenting, which I found funny and worrisome, but it's there.

**Comment by chrisinajar** [comment]
no that's shit, i want to play out 4v5's most of the time. Yesterday or the day before Xavice had to leave right before the final duel, *that game should count*.... One time melon and I won a 3v5, *that game should count*....

Imagine the anti-climactic feeling when you're winning, about to win, then an enemy leaves and the game just ends with no final duel, no last fight, no clean ending..... lame.

I also agree with Karmatic in that if you insta-lose MMR because a teammate rage quit or broke... that's shit... that feels so bad... if you care about MMR that's going to be extremely frustrating and demotivating.

PS: I read it before, mr smug, you just spoke a lot about the game post-DC so i assumed you had changed your mind :P

**Comment by KarmaticNeutral** [comment]
If I lose a game because my opponents hit 100 kills, I was part of the reason we lost. 
 I had direct influence over what happened in the game. 

If I lose a game because someone on my team DCed, I didn't do anything wrong.

I read exactly what you said and brought up my concerns. This exact issue. That a player who had no control over the outcome should not be penalized.

**Comment by chrisinajar** [comment]
I think we need to punish the players that do wrong, and let the other players go free so they can join a real lobby. No reason to punish people for landing on the wrong side of a team shuffle. There's no interaction, there's no team play, there's just frustration and a lower MMR....

**Comment by Haganeko** [comment]
Uh, Chris? I feel you didn't read it either. If a player left right before the final duel, you're safe unless that duel takes half an hour.

**Comment by chrisinajar** [comment]
then 3, whatever, you know what i mean, quit being difficult

**Comment by chrisinajar** [comment]
4 if it needs to be, *an amount* for *some time*

**Comment by Haganeko** [comment]
Or however long we decide it should be.

**Comment by chrisinajar** [comment]
exactly. you knew what i meant.

**Comment by chrisinajar** [comment]
also 1 player leaving should not take 30 minutes, that's crazy. Each player should have their own independent cumulative leaver timer of maybe 5 minutes max... and if any timer ever reaches 0 then the game is marked as leaver, no one else can lose MMR, and everyone can leave safely or play it out if they're having fun.

**Comment by Haganeko** [comment]
This is the thing I was talking about. This is not a solo game. No single player is responsible for their losses. Losing is not a punishment or such, it's something that happens. The loss is not to punish the team with the leaver, it's because (if the system and our game are well designed) you most likely will lose anyways if you have only two players left on your team. The punishment part comes from being assessed with an abandon.

**Comment by chrisinajar** [comment]
You are incorrect, 1 single player *IS* 100% responsible for the loss in this case.

Abandons mean nothing since we have no way of enforcing them.

**Comment by KarmaticNeutral** [comment]
what does being assessed with an abandon even do?
We can't prevent people from joining lobbies
We can't do Low Prio
We can't do anything with that.

**Comment by Haganeko** [comment]
Ugh. This sucks. Every time we debate something on Discord, we have it done, then people who never talked come and decide to complain on GH. Also 30 minutes was Cho's idea, we had originally thought about using ten.

**Comment by Haganeko** [comment]
We can make the mmr loss higher for people who abandon. I thought we already did that.

**Comment by chrisinajar** [comment]
All the more evidence that debating on discord doesn't work. I'm happy we're having the *real* conversation now.

**Comment by KarmaticNeutral** [comment]
First. Yes or No. Doy ou see the difference between losing at 100 kills and losing because someone disconnected. Do you see a difference?

**Comment by Haganeko** [comment]
We had the real conversation. The only reason you feel this is the real conversation is because your own opinion is in this conversation.

**Comment by Haganeko** [comment]
@KarmaticNeutral yes. One is quicker.

**Comment by KarmaticNeutral** [comment]
By real conversation he meant that discord sucks for debates like this.

**Comment by chrisinajar** [comment]
Indeed, it's important to include everyone. That's why github works better, it gives everyone a chance to wake up and chime in.

I would really rather talk about the mechanic at hand instead of this dumb shit though, can we get back to the topic please?

I love the idea of lowering MMR double when you leave, although I don't think it solves the case of the regular leaver since they already have insanely low MMR. It'll definitely help keep any player who cares from leaving, though...

**Comment by KarmaticNeutral** [comment]
Ok no that's not at all the real difference.
If you lose at 100 you had an impact. 
If you lose at DC, someone else did 1 action that meant nothing you did mattered.
Can you see that?

**Comment by Haganeko** [comment]
It does not. It's actually better because everyone can join in and take point, instead of it being me alone trying to debate three people at the same time. It's not fun.

**Comment by KarmaticNeutral** [comment]
Haga, Do you see the difference in what I just said?

**Comment by Haganeko** [comment]
One. Debating here means I constantly need to refresh the page since by the time I'm finished responding to one thing there's three new posts.
Two. If your mmr is in the trenches, your team won't lose much anyways because of how mmr works.
3. Do you have an impact if a teammate is griefing? Because that's what just leaving is.

**Comment by arrowpack** [comment]
We all see the difference pls stop asking

**Comment by KarmaticNeutral** [comment]
I will stop asking when he answers the question directly.

**Comment by KarmaticNeutral** [comment]
So, I'm taking that to mean you do see an difference and are bringing up a counter point that is a different issue that isn't being discussed in an effort to disprove a point with alternative problems that need a different solution.

We are talking about DCs not in game griefing. Please leave them separate.

**Comment by chrisinajar** [comment]
STFU unless it's mechanical related to this issue

**Comment by KarmaticNeutral** [comment]
Why did you delete that last comment? It was related?

**Comment by arrowpack** [comment]
How about we do the 5 min cap/safe to leave idea, and we add some mechanic to if like 3 ppl vote for someone, that player gets abbandonned, lose normal mmr, and the game continios. This way u dont rly suffer fro leavers and from trollers

**Comment by KarmaticNeutral** [comment]
That would be an issue to discuss in a different thread about what to do about in games griefers. This is about DCs.

**Comment by KarmaticNeutral** [comment]
If you don't have impact you shouldn't lose MMR. I don't understand how you can disagree with that.

**Comment by Chogex** [comment]
Usually when a teammate leaves, it's because the team is already losing or the player is having a bad game and gets frustrated. In that case the team was already more likely to lose and counting the game as a loss for the whole team is not too bad. However, sometimes the team is winning or the game is even and someone still abandons for whatever reason. Then it feels unfair to count the game as a loss. This is why I suggest having the system relate to how the game was going at the time of the dc.
Scale the mmr lost with xp/networth difference + score with a min cap of 0 or -1 mmr?

**Comment by KarmaticNeutral** [comment]
My only problem with that solution is that it doesn't account for comebacks which are common.

**Comment by Chogex** [comment]
The game wouldn't end immediately after someone dcs, but there would still be time to finish the game and have a possible comeback.

**Comment by imaGecko** [comment]
If you lose at 100 you did not have an impact if the loss was entirely brought by someone from your team leaving. A lost game is a lost game whether it ends at 100 or at whatever point the game is legitimately unwinnable. And if your shitty teammate wants you to have no impact on whether you win or not, be it leaving or otherwise, you don't have an impact in the game outcome, you are only prolonging the loss. This affects disconnects, griefers or just simply bad players.

That out of the way people do hate leaving and I'd prefer gg-ing out over safe-to-leave and having a legit game end. Perhaps enabling a gg option after someone abandoned the game if the losing team doesn't wish to continue. 

Alternative solutions would be a previously discussed lowered score limit from enemies leaving. So say the score is 50/25 at 100 limit. Losing team has their second disconnect so after a minute delay the score limit gets dropped to say 75.

For people having left the game, the leavers should get an autoloss either way, leaving may not always be your fault but always your responsibility. 

Safe-to-leave in my eyes mostly exists to just entirely abandon a game, outcome being secondary

**Comment by KarmaticNeutral** [comment]
Okay so I think everyone here is for the idea that the person who left, after a timer of some kind, loses MMR. (If we can somehow tell leaving from network issues we can double the leavers MMR loss)
Everyone Okay with that bit at least?

Then the debate comes to what to do afterward.

A reduced score limit sounds nice, but I don't think it solves the problem.
A gg option is interesting to me...
What if we combined it with what chris said earlier and make it so the losing team doesn't lose MMR but the winning teams does gain MMR? So if the game is bound to end a certain way, and a DC happens the losing team GGs out and the winning team gets their MMR.

**Comment by KarmaticNeutral** [comment]
But people can still fight for the win if they want?

**Comment by Chogex** [comment]
But then wouldn't that make it so that you'd always want one person to leave on the losing team so the other 4 wouldn't lose mmr?

**Comment by KarmaticNeutral** [comment]
In theory, but that's how vanilla Dota works. Do people do that in vanilla?

**Comment by imaGecko** [comment]
Making people not lose anything is abusable in itself. Losing something is fine, it's not a super hard punishment. The problem to be solved is mostly not turning dc games into such a drag.

Could do sort of a low-prio with players marked as such adding a lower mutiplier on gains/losses and the future ranked mode being disabled if a low prio player has joined the lobby.

**Comment by KarmaticNeutral** [comment]
we can't do low prio cause we can't control lobbies till the game launches. LP is not an option.

**Comment by imaGecko** [comment]
if only you read what i actually said

there's also other things you can do. a rehost vote where the game just ends with no results. would be quite useful if things ever go wrong during the picking phase.

**Comment by KarmaticNeutral** [comment]
I'm all for the rehost vote. Sorry I didn't respond fully. I was still processing everything you said. I was just saying LP isn't an option. Sorry I should have said something about still thinking about the rest.

**Comment by KarmaticNeutral** [comment]
How much do people gain/lose from a single match? Like could we make the penalty for losing with a DC like 10-20% of the normal penalty..?

**Comment by Chogex** [comment]
Instead of the rehost vote you could just make it so that if a player leaves the game before the first duel the game doesn't count towards mmr just like in dota with first blood.

**Comment by KarmaticNeutral** [comment]
I would say before boss spawns (first 3 minutes of the game) since the duel happens within 30 seconds of loading in and doesn't really leave time for issues to occur but I like that idea.

**Comment by imaGecko** [comment]
i didn't say lp, i said sort of lp. if a player marked as LP joins a game then the game counts for less and a ranked option which would be enabled in team select would be disabled (the game is already loaded in at team select when this would apply)

**Comment by Chogex** [comment]
That is pretty much what I've been suggesting karmatic neutral, except with a bit more convoluted system to make it so that you can't abuse abandons as easily to not lose mmr.

**Comment by Chogex** [comment]
If the game is safe to leave after the first duel, a ton of people would just abuse it and leave immediately if they lose the first duel.

**Comment by KarmaticNeutral** [comment]
My problem with that Gecko is people loading into a game they didn't expect to be in because they didn't know the person was marked and not being able to leave for fear of getting marked themselves.

That's true Chogex.... I just don't want someone who randomed into a stack to stop playing the game cause they keep losing MMR without playing a game (I have DCs in the majority of my games so I would be losing MMR all the time)

**Comment by chrisinajar** [comment]
If disconnects are timer based, we can just call the match if there's an abandon after `(X * 1.2)` minutes... lowering the score on disconnect is a great idea that i think should be added, but I do not believe that it is necessarily part of the "save to leave" feature.

As a quick show of hands for everyone watching this thread, and because i want to use reactions because they're fun...
👎 reaction for still losing MMR even if a teammate abandons
👍 reaction for no one losing MMR except the people who abandoned

**Comment by arrowpack** [comment]
👍just if someone leaves in the first like 5 min just auto rehost(had that been said already?)

**Comment by Chogex** [comment]
multiple times

**Comment by imaGecko** [comment]
I mostly just want games to end faster than they do now if the game is already over. A lost game is still a lost game to me, sometimes you just have no impact on the result,whatever the actual reason for it may be. 

Still losing mmr while also having a rehost option is my vote.

Also the thumbs down first totally threw me off

**Comment by KarmaticNeutral** [comment]
What bout if a teammate abandons meaning heavily reduce MMR lose like 20-25%? Is that an option?
Esp if we add what arrow just said again about early DCs?

That way it discourages leavers but doesn't penalize the innocent anywhere near as hard?

**Comment by KarmaticNeutral** [comment]
With a GG option thrown in for Gecko's last point?

**Comment by KarmaticNeutral** [comment]
- Once the threshold is hit, anyone disconnected loses MMR as if they lost and anyone still connected cannot lose more than 25% MMR dependent on game outcome.
- Whoever (connected players) wins the game should still get MMR as normal, even if it's the team which had disconnects. The losing team only loses a quarter of the normal MMR lost.
- We also implement a feature letting either team call GG like vanilla dota does in lobbied matches.
-If a player crashes/DCs before the first duel, there would be an option to rehost with either team gaining/losing MMR

This way dead games can end faster,
Players can't fully escapre losing MMR by have a player drop,
and The innocent don't take full flame to the face.

Thumbs up if you like this compiled solution
Down and a comment if you have any problems.

**Comment by arrowpack** [comment]
![screenshot_20180201-192819](https://user-images.githubusercontent.com/34633158/35695942-3b0b649c-0786-11e8-9203-82acf10173c0.png)
Is this the solution?

**Comment by KarmaticNeutral** [comment]
LOL what?????

**Comment by KarmaticNeutral** [comment]
and DC players receive this new cooldown thing?

**Comment by Haganeko** [comment]
Regarding the situation with a player DC'd
We have a problem: when one or multiple players DC, the game can drag on, making it so the players on both sides feel forced to stay in a game with a foreseeable outcome. On one side, the players on the team with more players want to stay and get the win. On the other, the players on the team with less players may want to delay and bore the other team into leaving, thus getting the win.
In order to resolve this situation, we need to make the game safe to leave. This means that there must be no incentive to stay, be it negative (a penalty for leaving after the game is "done") or the possibility of gaining something (say, if one manages to bore the other team into leaving as a whole). So there can be no further MMR or other rewards to fight for. Any MMR changes must be decided at the moment the game is declared "safe to leave".
As for whether the team with less players should be regarded as losing, there seem to be two views: either no MMR would be deducted from the leavers' teammates or they'd be levied with a loss. The argument for the first seems to be that the players do not have any fault in their teammate leaving, and so shouldn't lose MMR for it. The problem with this argument, as Gecko argued, is that no player can ever be guaranteed they'll win or lose MMR on their sole skill and agency. This is not how the game works, and creating a system which rewards having a teammate leave when losing creates perverse incentives.
On the other hand, the team without leavers must be granted a win, so as to disincentivize leaving as a way to spitefully deny the opposing team victory MMR when losing.

**Comment by Haganeko** [comment]
KN asked me whether I saw the difference between losing to 100 points and losing due to someone losing. Clearly, the player has more agency on the loss to points... though not much, because in a team game a single player making a single mistake at a critical moment can lose a game. That's the nature of teamwork.
The problem, though, is that this does not apply to the context we're discussing: the context of what to do once someone has left. With that as the premise, losing to points also becomes even lower in terms of agency, since the odds are very much stacked against the team for every player they are lacking.
In terms of player perception, in both cases they'll have lost due to the leaver - unless the game was already effectively lost before they left, in which case the point is moot.

**Comment by Haganeko** [comment]
Having thought about it, this is the best way I see to deal with this:
If a player abandons before bosses spawn, the game is null and void. No stats are recorded, but that player is issued an abandon and a loss.
After that, once a team accumulates N collective minutes of leavers, declare that team loser and the opposing team winners. They may still play the game, but it is safe for everyone to leave. They risk nothing by doing so.
It has been pointed out that DotA lets the teams still play after the game is "safe to leave". However, DotA is much more fun and quicker to finish against a turtling team. Playing OAA while the enemy hides in their cave is a drag. This also has the disadvantage that, even if we introduce mechanics that make it harder to turtle, the game will be very unfun for the players in the losing team, who will likely hopelessly struggle because there's still the possibility of a win there. No one likes to get stomped.

**Comment by Melongod** [comment]
My current problems with the proposed system are as follows: 
1. Giving a team a blanket loss because someone on their team baby-raged is giving the person who leaves MORE POWER. We all know how toxic people behave and giving them the ability to lose not only their own MMR, but everyone else's too is just playing into their hands. This will cause **FAR** more problems than it would fix and it **WILL** cause players to leave. This cannot be aloud under any circumstance.
2. Aside from the issue mentioned above, giving a blanket-loss to a team before the end result of a match is just bad game design. I know that many X v 5 games occur and winning them is always hard fought. In DotA, this is equivalent to a team winning after battling against mega creeps. Chris and I have won many games both 3v5 and 4v5. There is **NO** greater feeling than winning when the odds are stacked against you, and slapping a time limit onto these situations makes winning them nigh-impossible.

My counter proposal is such that:

- If a player abandons before the first boss is taken, the game is null and void. No stats are recorded, but that player is issued an abandon and a loss.
- If a player abandons after that, they are **MASSIVELY** punished. A proposed sufficient punishment is that they lose mmr = the total mmr gained by the winning team at the end of the game. Perhaps that is too harsh, but I feel that the severity should be treated thusly)
- Anyone who abandons after that point receive a loss, but do not lose MMR as per the current system in DotA. This is also true for the team who did not have anyone leave.
- All players who remain in the game until it concludes will be treated normally (win = gain, lose = lose).



Semi-related; I'm unsure as to the solution for idling and cave clearing, mainly due to my lack of knowledge of the bounds of LUA to detect such things. Some heroes just like clearing cave over and over and over again such as Lich. That problem is FAR more complicated but isn't as prevalent as the abandoning problem so I feel that it should be dealt with separately.

I also wholeheartedly agree that the score limit should be decreased by an amount when a player leaves.
My proposed solution is that when a player leaves, the score limit is decreased by X% of the starting score (s) minus the winning teams current score (w).
`(x/100)*(s-w)`
I'd propose that x=20
What this achieves is that the earlier a player leaves, the more time is saved.

An example of this, assuming x = 20 and that it is a normal-sized game:
- If a player leaves when the score is 80 to 20, then the score limit goes down to 96. 
- If 4 people leave and 1 person stays, then the score limit goes down 84, which is **VERY** achievable by bosses and doesn't waste much time.

Another example following the same assumptions:
If a player leaves when the score is 30-5, then the score limit goes down to 86.
If 4 players leave and 1 stays, then the score limit goes down to 44. This is also **VERY** achievable through taking bosses especially if it's that early in the game.

**Comment by Trildar** [comment]
Regarding idle detection. The Cave and Fountain are already zoned, so it shouldn't be too hard to detect players spending time there. There could be some sort of time limit to being in those areas when a player has abandoned. Possibly also tied to there being no kills outside of Duels for some time. Then again, there are also plans to speed the game up by granting points for Cave clears and Duel wins. That, together with reducing the score limit when people leave might be enough that anti-hiding mechanics to prevent people from dragging lost games won't be necessary.

Somewhat related, we should probably also implement AFK detection.

**Comment by Melongod** [comment]
Massively updated my post, plz re-read.

**Comment by Haganeko** [comment]
With regards to Melon's analysis:
1. This gives toxic players no more power, since no matter what you do they can still make you lose by feeding on purpose or doing other such things. I'd rather they abandon than stay and make the game miserable. 
2. The whole point here is to make people leave lost games. If you say there is a decent proportion of 3v5s which can be turned, then we only implement safe to leave once it's down to 2v5.

About his proposal:
1. Agreed. 
2. This is not about punishing leavers, it's about making the game safe to leave. This also does not address accidental leavers, or people who disconnect but do not abandon. As for the first, I assume they are acceptable casualties in your system. For the second, I guess you'd have a timer to auto abandon them? 
3. As I said before, if there is a potential mmr gain on the table, it is not safe to leave. We want people to let go and play another 5v5, not stay and fight that 1v5 to the bitter end. 
4. So everyone (after the first) on the losing team DC's on the final duel anyways to avoid losing any mmr?

**Comment by Melongod** [comment]
Revised proposal

- The first player who abandons are punished. 
- If a player abandons before the 2nd duel, the game is null and void. No stats are recorded, but that player is issued an abandon and a loss.
- Anyone who abandons after that point receive a loss, but do not lose MMR. This is also true for the team who did not have anyone leave.
- All players who remain in the game until it concludes will be treated normally (win = gain, loss = lose).

A proposed sufficient punishment for people who abandon is that they receive a penalty on earned MMR and Bottle Pass xp. (With mmr, change the k value)

**Comment by Haganeko** [comment]
That does not incentivize people to just leave the abandoned game.
It also certainly causes mmr inflation because all the losing team's players will DC at the last moment to avoid losing mmr.

**Comment by Melongod** [comment]
It most certainly does if the score limit decreases when people leave.

**Comment by Haganeko** [comment]
No, because there's still mmr on the table. Why would you leave if the mmr is there to fight for?

**Comment by Melongod** [comment]
if the losing team all leaves to avoid losing mmr, then they **ARE** incentivized to leave.

**Comment by Haganeko** [comment]
They'll only leave once the kill limit is reached, after the winning team has had to kill some twenty bosses and camp their spawn for a couple ages. And then they'll leave on the final duel.

**Comment by Melongod** [comment]
did you even look at the numbers on the score limit decreasing issue?

**Comment by Haganeko** [comment]
Hard to look at that colorful image on a mobile phone. But going by the formula you posted, after four quitters in a game at 20 kills, you'd need another 16 points, no?

**Comment by Melongod** [comment]
yes.

**Comment by Melongod** [comment]
perhaps this part of the discussion should be taken to that issue.

**Comment by l34Um1** [comment]
1. Each player has a 5 minutes indivdual timer for abandon like in Dota.
2. First player to abandon loses MMR.
3. The game is then marked safe to leave.
4. If a player leaves they still get full Bottlepass experience. They don't lose MMR.
5. Duels are no longer balanced to be even. If the match is 3v5, then duels are fought 3v5.
6. If all players from one team leave or the game ends via final duel, the winning team gets MMR.

Keeps it simple.

**Comment by Haganeko** [comment]
The main issue we're trying to solve is the game where this one person stays in a 1v5 and mostly durdles around in their base, forcing the other team to either kill a billion bosses or leave and thus concede them MMR.
I suggested a way to make this strategy inviable; Melon and Chris, a way to make the period of time during which this happens shorter.
Your idea does neither.

**Comment by l34Um1** [comment]
Yeah it does. My idea makes it unfun. Also who cares if the enemy gets MMR. You aren't losing any, that's all that matters.

**Comment by Melongod** [comment]
That's also all covered by my idea.

**Comment by Haganeko** [comment]
Implementation issue is up. Closed.
