### ISSUE TITLE
Reddit post

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1922]
Title: Reminder: The Sign Ups for the $10,000 Custom Game Tournament are still open for one more week!

# The Signups for the Open Angel Arena Anniversary Tournament with a $10,000+ Prize Pool Will Only Be Open For One More Week!

We have surpassed our expected count of 32 teams. In response, we hope to reform the event to enable more teams to compete. However, before we can do that we need to reach a full roster of 64 teams. 

This is your moment to show us what you're made of. Open Angel Arena is a new game with a young community. It is highly competitive but there are no pro players. There are only people like you and me competing. So if you ever wanted to earn money playing video games and get your share of a $10,000 prize pool, now is your chance.

Sign up while you can as we will be closing sign ups on February 10th. The tournament will take place on March 3rd and 4th, so even if you only start playing now, you will have enough time to learn the game!

### We are still working on the game!
We have implemented a ranked system similar to the dota MMR system into our game mode. You can check your MMR and the top 100 leaderboards at [oaa.gg](https://oaa.gg/).

The Dev team is working hard to create the "Bottlepass", a personalized, free version of the Battlepass that rewards loyal players with cosmetic unlocks ingame!

If you are interested in signing up, or wish to just know more, then follow these links:

* [Rules](https://docs.google.com/document/d/1YJj_oRRLvmC6zvKQxBmg4yDZVesrJOqjJokESea2tIM/edit?usp=sharing)
* [Sign up](https://docs.google.com/forms/d/e/1FAIpQLSeOVXbT1gyXzOEQDL2sEFQ1mD_sz08Y9NmRnMVziN7FTNBjZQ/viewform)
* [OAA.gg](https://oaa.gg/)
* [Previous Reddit Post with more detailed information](https://www.reddit.com/r/DotA2/comments/7soifz/announcing_the_open_angel_arena_anniversary/)

Open Angel Arena is currently game of the day. So if you ever wanted to try it, now is your best chance!

Thank you for your continued support!

**Comment by Haganeko** [comment]
I don't think it's wise to commit to a 64 team bracket with only 41 inscriptions. It is not unlikely that we get seven more and have to give bys to a third of the teams in the first round

**Comment by KarmaticNeutral** [comment]
# The Signups for the Open Angel Arena Anniversary Tournament with a $10,000+ Prize Pool Will Only Be Open For One More Week!

We have surpassed our expected count of 32 teams. In response, we hope to reform the event to enable 64 teams to compete. Unfortunately, we can't do this until we reach a full 64 roster. Hurry to sign up. We will be closing signups on February 10th.

Since the announcement post, a few new BIG steps in oaa’s development have occurred. 
We have implemented a ranked system similar into the dota MMR system in our game mode. You can check your MMR and the top 100 leader board at [oaa.gg](https://oaa.gg/).
The Dev team is hard at work in the creation of the bottle pass a personalized, free to everyone version of the battle pass that rewards loyal players with cosmetics in game!

If you are interested in signing up, or wish to just know more, then follow these links;

[Rules!] (https://tinyurl.com/OAAOfficialRules)
[SignUps!] (https://tinyurl.com/OAATournamentSignups)
[OAA.gg] (http://oaa.gg/)
[Previous Post] (https://www.reddit.com/r/DotA2/comments/7soifz/announcing_the_open_angel_arena_anniversary/)

Thank you for your continuing support!
