### ISSUE TITLE
Poop wards and scan occasionally don't work

### ISSUE THREAD

**Issue by Melongod** [OpenAngelArena/oaa#1976]
You are still able to press your hotkey for glyph and it sometimes actually uses glyph instead of dropping a ward. I have a feeling that if this happens then all allied poop wards will go on cd.

**Comment by Trildar** [comment]
Technically, Glyph goes on CD, and because of the way the stuff is implemented, you can't use Poop Wards when Glyph is on CD.

Really need more information for this to get any idea as to what the cause may be. Though there's always just the option of making the command interception clientside, which we eventually want to do anyway, assuming it's possible.
