### ISSUE TITLE
Zeus Cloud attacks too fast

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#198]
Will fix today. I buffed the cloud, turns out his cloud attacks so fast that his passive can almost permastun an entire team. I am going to keep the attack rate from normal dota.

**Comment by warpdragon** [comment]
Actually nevermind. I can't find out why the cloud attacks so fast. The default `"zuus_cloud"` ability and `"npc_dota_zeus_cloud"` unit only list a single set of values. There's no progression built-in at all. I was mistaken about having edited this. The cloud simply shouldn't be behaving the way it is.

**Comment by Haganeko** [comment]
The cloud is affected by CD reductions from Zeus. So if he has a refresher core, and casts triple nimbus...

**Comment by chrisinajar** [comment]
triple nimbus is allowable by design, CD reduction on nimbus could be what's causing the rapid bolts...

It could also be that there's a unit somewhere for the nimbus which has it's attack speed changed?

**Comment by Haganeko** [comment]
Just gotta nerf refresher core. Percentage based CD reductions affect Nimbus; that's from vanilla. The problem is that when CD is reduced by 60%, the nimbus shoots every 0.9s. With three nimbus es,  that's one bolt every 0.3s on average - enough to keep people stunned - after all, bolts stun for 0.2s...

**Comment by Haganeko** [comment]
Close this? We're reworking Refresher Core.

**Comment by Chronophylos** [comment]
I think it was fixed.....
