### ISSUE TITLE
Wraith King's Ult does not respawn him during duels

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#201]
Supposedly the duel always treats WK's first death as duel ending and prevents him from repsawning.

**Comment by chrisinajar** [comment]
There's some sort of isReincarnating flag on heroes, when a hero dies you should check that flag and allow them to respawn if it is set, otherwise count the point and move on.

Additionally, it's possible that killing a reincarnating wraith king falsely counts for a point, that should also be fixed.

**Comment by Chronophylos** [comment]
Why did you reopen this?

**Comment by KarmaticNeutral** [comment]
because we had 4 reports of it occuring today during the open session

**Comment by Chronophylos** [comment]
Ah ok

**Comment by KarmaticNeutral** [comment]
definitely broken. Also, it tries to respawn him, but the duel is over so he gets stuck outside.

**Comment by Chronophylos** [comment]
So WK trys to respawn but the duel is over?

**Comment by KarmaticNeutral** [comment]
yes

**Comment by warpdragon** [comment]
This is resolved?
