### ISSUE TITLE
Circle under character is weird

### ISSUE THREAD

**Issue by dkNykita** [OpenAngelArena/oaa#207]
On this exact spot circle under character is being weirdly deformed.

![circle](https://cloud.githubusercontent.com/assets/26550793/24111044/787d975a-0d95-11e7-8608-554339df383e.png)

**Comment by dkNykita** [comment]
Also this position is weird

![circle_2](https://cloud.githubusercontent.com/assets/26550793/24111210/061f17c8-0d96-11e7-838c-13a0c25640b3.png)

**Comment by Chronophylos** [comment]
Looks like the unmovable terrain or the navmesh isn't set right...

**Comment by dkNykita** [comment]
Another one

![circle_3](https://cloud.githubusercontent.com/assets/26550793/24112264/47fed482-0d99-11e7-9695-b7225fc4c355.png)

**Comment by dkNykita** [comment]
And another one
![circle_4](https://cloud.githubusercontent.com/assets/26550793/24113864/7545b910-0d9e-11e7-8fbb-87ec3d162176.png)

**Comment by dkNykita** [comment]
There are more of them
![circle_5](https://cloud.githubusercontent.com/assets/26550793/24115444/aabeb1f0-0da3-11e7-8793-c597d290f927.png)

**Comment by warpdragon** [comment]
We still haven't figured out why it does this. I've tried changing the terrain and the tileset, doesn't seem to fix it. I will say that the colosseum tileset results in worse artifacts than the normal tilesets, but they both do it. I'm not sure what the fix is. I'll keep looking into this as the map progresses.

**Comment by l34Um1** [comment]
Closed because old.
