### ISSUE TITLE
New Mirana level 25 Talent | 5€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2160]
"Global Range Sacred Arrow".

As the name implies the arrow now has global range. This does not increase the damage or stun duration of the arrow. It simply makes the arrow not have a maximum travel distance and gives it global cast range.

This talent replaces "-80 Moonlight Shadow Cooldown".

**Comment by AbitTheGray** [comment]
Gonna try it.

**Comment by AbitTheGray** [comment]
Ready but still require in-game test and setup git for pull request.
And no, I did not forget to implement arrow multi-shot or cooldown reduction.

**Comment by AbitTheGray** [comment]
Status:
- Multishot works, can also add more then 2 arrows
- Arrows do not trigger on hit
- Arrow stun not implemented (but calculated), deals only damage (if only on hit trigger work)

**Comment by AbitTheGray** [comment]
Finally got it working.
Gonna PR in about a day (still need to prevent multiple arrows (lvl 25 talent) to hit same unit) but it is working!

One small but will appear because ExtraData of projectile cannot transfer Vector (which did not cause the problem but I needed to fix it too).
With refresher (or WTF) you can get maximum arrow damage/stun by recasting it further away the target before the first arrow hits. This is because each cast resets start (cast) location which is referenced by arrows to calculate stun duration.

**Comment by DarkoniusXNG** [comment]
This can be closed.
