### ISSUE TITLE
Phase spark/boots deal 100% splash dmg instead of 50%

### ISSUE THREAD

**Issue by Larenall** [OpenAngelArena/oaa#2598]
What title says. Just change few numbers, And while we are at it buff power spark/boots, they are shit rn. And there is no point on having lower stats on power spark/boots for ranged heroes.

**Comment by SquawkyArctangent** [comment]
```
    -- generate damage stuff
    local damage = keys.original_damage
    local damageType = DAMAGE_TYPE_PHYSICAL
    local damageFlags = DOTA_DAMAGE_FLAG_NO_SPELL_AMPLIFICATION
    local damageMod = ability:GetAbilityDamageType()
    damage = damage * damageMod
```

y'know

i think this is a pretty wonderful story i've unintentionally told in this code

**Comment by Larenall** [comment]
@SquawkyArctangent I didn't quite get what u r trying to say as im not common with the programming language

**Comment by SquawkyArctangent** [comment]
the old phase boots kv didn't have a damage type kv, because it didn't need to with its instant attacks

so when i started working on 'em, i hardcoded in the damage type i was testing so i didn't have to reload oaa from scratch and update the values from kv

so everything was fine and dandy, and i just had to finish it up by replacing the hardcoded damage type with ability:GetAbilityDamageType()

... but apparently, when i actually did it, i left the damage type the same and instead replaced the _damage multiplier_ with the damage type

fortunately damage types are just integer constants and physical damage is 1, so the only result was the damage not being modified at all, but


w h o o p s

**Comment by Larenall** [comment]
Now i get it
