### ISSUE TITLE
Add modifier for bottle that shows how many bottles you have collected throughout the entire game

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#263]
I'm pretty sure you can just store the value on the hero entity

 * Only show when you have a bottle currently
 * Only count a bottle as being collected by a hero once
 * Count all bottles collected through the entire length of the game for each hero

**Comment by Chronophylos** [comment]
Why?
You could use a [`InventoryFilter`](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API/CDOTABaseGameMode.SetItemAddedToInventoryFilter).

**Comment by chrisinajar** [comment]
seems like a great way to implement it, you'll just have to add in the modifier and deduplication code from there :+1:

**Comment by Trildar** [comment]
Why do we keep acting like we seriously want to keep having a bunch of bottles dropping from creeps? XD

**Comment by chrisinajar** [comment]
"acting"? 🤔

**Comment by Chronophylos** [comment]
We even tried stacking bottles...

**Comment by mokonaDesu** [comment]
Isn't gold gain is out of whack because of all the bottle drops? I think i got an idea to prevent the bottle abuse:

Using this InventoryFilter we might just make it so that any existing bottle is removed before adding a new one. We'll put the new bottle in the same inventory spot after that This is going to look as if the bottle is refilled, but in fact, you'll only be able to have just one bottle at a time. The modifier would then increment letting everyone know how much of a bottle hoarder you are.

**Comment by Chronophylos** [comment]
I made everything except the modifier....
I don't know how to do that.
