### ISSUE TITLE
Tree optimisation

### ISSUE THREAD

**Issue by Larenall** [OpenAngelArena/oaa#2653]
![Items](https://user-images.githubusercontent.com/34693826/58824462-cc009880-8644-11e9-95a8-384e28a5600d.png)
S&Y&K =S&Y and S&K and Y&K
Not 1 item, but 3

**Comment by chrisinajar** [comment]
imo bloodthorne should still build out of orchid. bloodthorne is just a better orchid, it feels very natural. I'm down for orchid -> bloodthorn without an orchid 2 for sure.

I am extremely opposed to S&Y&K, it would require nerfing all the values to account for the additional ones and also removes an interesting choice from item buildups. I vastly prefer 3 strong (XYZ)&(XYZ) items over 1 medium X&Y&Z. We deliberately removed all of the original "item combinations" (refresher core, shivas cuirass, shroud of shadows, etc) as opposed to nerfing them because we realized all they did was remove choice and make item builds more cookie cutter.

I dig the rest, especially mkb :+1:

**Comment by Larenall** [comment]
S&Y&K =S&Y and S&K and Y&K

**Comment by Larenall** [comment]
> We deliberately removed all of the original "item combinations" (refresher core, shivas cuirass, shroud of shadows, etc)

What is shivas cuirass? Was there such a custom item? If u mean shivas and AC then can be build w/o a core.

**Comment by Larenall** [comment]
Whats the point of having Bloodthorn from t1 core, it not even that good to restrict it that way. 
Random idea that came to my mind just now, why not have Orchid build up into Bloodthorn of Hex item tree(euls, atos, memhammer).
![Ochid](https://user-images.githubusercontent.com/34693826/58830279-a5495e80-8652-11e9-8982-9cd48e2c7f0b.png)

**Comment by POCKETMONEY99** [comment]
I think dragon lance should just be removed as an upgradeable item. Its so bad. The only way it would ouclass hurricane pike is if it gave way to much stats and then it would likely be purchased on melee cores along with ranged cores.

imo the tree should be 
-Pike 1
-Pike 2
-Pike 3
-Pike 4 - Giant Form 1
-Pike 5 - Giant Form 2

**Comment by Larenall** [comment]
> I think dragon lance should just be removed as an upgradeable item. Its so bad. The only way it would ouclass hurricane pike is if it gave way to much stats and then it would likely be purchased on melee cores along with ranged cores.
> 
> imo the tree should be
> -Pike 1
> -Pike 2
> -Pike 3
> -Pike 4 - Giant Form 1
> -Pike 5 - Giant Form 2

fully agree

**Comment by POCKETMONEY99** [comment]
I think bloodthorn should be a tier 1 item because orchid is fairly weak in OAA, because you can easily get a dispel on any hero in ~2 minutes without fail. The mana regen barely matters and the stats are medicore compared to other tier 1 items. 
Honestly on heroes I even want a bloodthorn on I would still go daedalus level 1 and 2 because orcid is a waste of a slot if you require cores to upgrade it into bloodthorn.

**Comment by Larenall** [comment]
Soooo.... Can anyone do this?

**Comment by POCKETMONEY99** [comment]
I started working on it a few days ago. I will finish it today or tomorrow.

**Comment by POCKETMONEY99** [comment]
I have done all of this but I put nulllifier in a tree with more simillar stats across the options (Daedauls/Bloodthorn). I also haven't added manta style into the sange/yasha/kaya tree because heavens halberd would need to be in their for consistency reasons. Also I feel that if you want to swap your manta style for a Sange and Yasha etc, manta needs a buff.
