### ISSUE TITLE
Shadow Shaman and Warlock ult buffs

### ISSUE THREAD

**Issue by Larenall** [OpenAngelArena/oaa#2665]
Shadow Shaman
Serpent ward dmg to 100/200/300/450/600
talent changes
lvl 25 talents +1 Serpent ward hp or 400 Q dmg
lvl 20 talents  +50 MS or +2.5 Shackle durration
Serpent ward dmg was useless
Buffing the talent? 
A: buff wards -> with talents wards will do too much dmg
B: dont buff wards  -> Wards are only good with this talent( b4 lvl 25 ur ult is useless)
Imo best decision is to remove it and MS is always a nice stat

Warlock
Golem
HP 1500/2750/4000/7000/10000
armor 10/20/30/40/50
dmg 100/200/300/550/800
Hp regen 30/60/90/150/300

Aghs golem
hp 1000/2000/3000/5500/8000
dmg 75/150/225/400/575

Golem`s Flaming fists dmg 
40/80/120/160/200

No more paper golems

**Comment by POCKETMONEY99** [comment]
Witchdoctor also has a similar problem to shadow shaman. They have wonky powerspikes with their ults due to them only really being good when then reach 25. (Witch doctor ultimate is actually redundant unless you take the level 25 talent). 

But I like the idea of trying to smoothen out Power levels of spells without talents or OAA levels. A spell should definetly be useful without a talent.

**Comment by Larenall** [comment]
Ults of some heroes in oaa are at dota power lvl, not at oaa power lvl, its a problem that requres fixing.
