### ISSUE TITLE
Improving New player Experience 

### ISSUE THREAD

**Issue by POCKETMONEY99** [OpenAngelArena/oaa#2724]
Main Issues I see with new players. (There are more but this is the main 3 which ruin player retention. 

**Issue:** 
No idea what to do with upgrade cores/ how to get them. 
**Solution:**
Update the information tab ingame (I will do this if somebody can show me the file location). It hasn't been updated since farming cave which is really bad, considering how much the game has changed. 

**Issue:**
They never have any gold, because they think this game operates like other angel arenas, where your buying cleave to flash farm camps. Additionally there arent any fools gold boots for carries leading to alot of new players to buy phase/power on semi carries (BH, URSA, WR etc) 
**Solution(s):**
Make all boots give a uniform amount of passive GPM. (600, 1800, 3600, 4800, 9600 or something). Also make the amount of gold creeps give less. This will help reduce the insane early game snowball some heroes can achieve as everyone will have a simillar networth. Creeps are now mainly an exp resource. This could also make games more fun for new players as they are less likely to get stomped by a level 20 6 slotted carry at 10 minutes when they have 2 items. 
OR
Make all the Dota boots Fools gold boots (Passive GPM, easiest to understand), then make the farming boots custom OAA boots. People will be more likely to opt for what they are familliar with, so they will have gold guaranteed. 
OR
Increase everyones passive gold and remove the gold gain from boots. Item upgrade costs would need rescaling if this happened. 
(Also make BoTs not completely worthless.)

**Issue:** 
Poor item builds. You can't go the same items you would in dota and have the same game impact.
**Solution:**  
Add custom item builds (I think somebody has done this already)

**Comment by DarkoniusXNG** [comment]
1) Info tab is up to date actually just nobody reads it. There are no mentions about bounty runes though. If you want to edit an info tab tooltips, its here: https://github.com/OpenAngelArena/oaa/blob/master/game/panorama/localization/addon_english.txt

2) I was thinking to increase Periodic gold (passive gold per second) actually because currently it lower than normal dota: 1 gold every 5 second (in normal dota its 1 gold every 0.66 seconds). Also Yearning Spark is supposed to give 500 passive GPM, unless its bugged.
You have some good ideas. Fool's gold boots should have no penalty and Farming boots should give bonus gold when killing creeps. All fool's gold should have a same effect (bonus GPM or gaining charges and then bonus gold on kill). I will think this through. But if this gets implemented, every creep should have slightly reduced gold bounty.

**Comment by POCKETMONEY99** [comment]
I remember that fools gold was going to be removed but nobody got round to reimplementing the boots. But a large boost to passive GPM and a reduction in creep bounty may help level the playing field early game. New players are less likely to run into games where the enemy carry is quadruple their networth at 10 minutes if they have alot more gold.
