### ISSUE TITLE
Is it possible to do development on mac os ? 

### ISSUE THREAD

**Issue by srxzr** [OpenAngelArena/oaa#352]

**Comment by DoctorGester** [comment]
Short answer: no

**Comment by srxzr** [comment]
no Linux too ? :(

**Comment by DoctorGester** [comment]
Please consider reading the official Valve wiki: https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Installing_and_Launching_Tools

**Comment by Chronophylos** [comment]
I haven't tested this yet but you could try to use Virtualization Software like qemu or VMWare.

**Comment by chrisinajar** [comment]
wine doesn't usually work because half of valve's stuff runs through wine, so it's all super wine aware, and it hides shit it knows doesn't work.

Since you can launch the vconsole, you can still launch the mode locally, but you can't edit any panorama stuff or map related things without the use of the tools. Also it's a bit painful to try and develop without the proper debug console you get in the workshop tools.

**Comment by chrisinajar** [comment]
That said, there are a few things like translation integration that actually require linux or osx to develop on.

We also want to, at some point, start developing our own stats tracking. If this is something that interests you and you know how to do well, you and I should have a conversation and plan out some stuff. Otherwise I look forward to your OAA contributions!

**Comment by warpdragon** [comment]
Honestly the majority of what I do can be done on any computer with a text editor, osx, linux, winblows, hell even a phone (i do 90% of my work on Linux and it's really nice).  It all depends on what part of the project you intend to help.  Also I'm fairly certain you can still debug using the default Dota2 console, right?
