### ISSUE TITLE
Have a test build available on steam with a random name

### ISSUE THREAD

**Issue by darklordabc** [OpenAngelArena/oaa#381]
I'm suggesting having the latest or semi-recent test build available online, with public settings, but with a random name. This is so people can easily test the game and hopefully greatly increase the rate of feedback. 
Right now testing is hamstringed by the fact that games have to be uploaded every-time we want to test, and players have to know each other on steam if they want to be able to join the game, I've tried to join a couple of test games but when I saw the lobby, I couldn't join the game because I wasn't steam friends with the host, resulting in me just moving on. 
E.g. if there was a "public" build there would probably be 1 or 2 games of testers playing it right now, as of currently there is zero games (to my knowledge).

**Comment by chrisinajar** [comment]
Right now bug testing has basically been invite-only via my friends list. I add new testers about daily, but as more things get working and the game develops further it might be a good idea to rotate out official public test builds under obfuscated names.

It would be really important to monitor the subscriber count and make sure people aren't catching on, since we don't want people actively _playing_ the game.

I think it's a good idea but i'm not sure if we need it yet. The bug testing team has been able to consistently get 2v2's and 3v3's going most days, and on weekends we can easily get full 10-stacked games.
