### ISSUE TITLE
Item duplicates can't be purchased from shop

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#394]
If you already own an item and want to buy a secondary duplicate, you have to buy the items individually. You can't bulk buy them or you will get just the recipe.

**Comment by KarmaticNeutral** [comment]
https://www.youtube.com/watch?v=Pxeh6ALZkt0&feature=youtu.be

More details thanks to M-

**Comment by darklordabc** [comment]
This is because of:
"UpgradeRecipe" "item_recipe_assault"
Its telling the game that to upgrade the item you only need to buy that recipe. This flag is used for dagon and necronomicon, so when you right click a dagon, if you already have a dagon it just buys the recipe, however, the assault cuirass needs more than just a recipe to upgrade so it does nothing. I think we can remove the line and it should fix this problem.

**Comment by Haganeko** [comment]
Is this fixed here: https://github.com/OpenAngelArena/oaa/pull/460 ? Maybe change the labels to testing needed?

**Comment by Chronophylos** [comment]
Should be fixed.

**Comment by KarmaticNeutral** [comment]
My PR fixed this as far as I can tell
