### ISSUE TITLE
Update Talents

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#475]
We have a bunch of talents which need to be changed. List of what needs changing attached.
[Talents.pdf](https://github.com/OpenAngelArena/oaa/files/907144/Talents.pdf)

**Comment by spar36** [comment]
@Trildar I was looking at the talents to see how easy it would be for me to put them in this weekend.

Did you hand make them, or find them somewhere? We will also need all the heroes that have a respawn time talent.

*Plus if it is easy, having all the heroes would be nice 1) to see what all the talents look like in KV, and 2) if we want to change any others later, the files would be there.

**Comment by Haganeko** [comment]
If we do the talents as they are here, some will take serious work. Do the easy ones for now - balance and design shifts may change these.

**Comment by Trildar** [comment]
@spar36 I've not actually changed anything myself yet. I just put in the hero KVs with their talents so that they can be changed later. They all currently point to their default talents. Vanilla Talent KVs can be found [here](https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/scripts/npc/npc_abilities.txt).

As for adding all heroes. That's probably scriptable, but I'm not too sure how to do it. Plus, I don't personally see much advantage in having all hero KVs in there just for the sake of having them available, mainly because I think it makes things more annoying when vanilla Dota changes hero's Talents. The KVs themselves aren't particularly interesting, just ability lists. The Talent KVs usually just have a single value in their AbilitySpecial.

Most if not all the Talents that change specific ability values will probably require rewriting the abilities. The more generic stuff like +stats and +spell amp can reuse the existing vanilla Talents, and possibly use `BaseClass` for creating ones with values that don't exist in normal Dota.

**Comment by spar36** [comment]
Here is the link to a spreadsheet that says what is done.
All of the "add" heroes can be done, just will take time to put them in by hand.
All "special" heroes will require an ability to be created.

https://docs.google.com/spreadsheets/d/1l7yKkpZlyLGWE-gyBBwEjGVK8InvrezDPFy8UPXfisk/edit?usp=sharing

**Comment by Haganeko** [comment]
[Talents706.pdf](https://github.com/OpenAngelArena/oaa/files/1006113/Talents706.pdf)
Updated talents table, with all the RT talents removed, and the techies problem fixed.  Also moved one or two of the RT talents into Gold or XP talents when they were of the same level, because the RT substitute was cooler.

**Comment by Haganeko** [comment]
[Talents706.pdf](https://github.com/OpenAngelArena/oaa/files/1009532/Talents706.pdf)
Updated with the Magnus thing.

**Comment by Haganeko** [comment]
Invoker level 15: +2 mana regen.

**Comment by Haganeko** [comment]
Where are we on this?

**Comment by warpdragon** [comment]
afaik this is done, or atleast in a good place. closed.

**Comment by Haganeko** [comment]
It's not. A lot of ability re-implementations are still necessary.

**Comment by Zarnotox** [comment]
Is there an update for 707?

**Comment by l34Um1** [comment]
Closed because old. We should make a new issue if this is a concern.

**Comment by Haganeko** [comment]
There will be, when I have the time, and we should.
