### ISSUE TITLE
\sellblacklist\filter.lua:21 attempt to index local 'target' (a nil value)

### ISSUE THREAD

**Issue by RamonNZ** [OpenAngelArena/oaa#484]
This appears to happen every game:

[VScript] Script Runtime Error: scripts/vscripts/components\sellblacklist\filter.lua:21: attempt to index local 'target' (a nil value)
stack traceback:
	scripts/vscripts/components\sellblacklist\filter.lua:21: in function 'fun'
	scripts/vscripts/libraries\fun.lua:30: in function 'gen_x'
	scripts/vscripts/libraries\fun.lua:586: in function 'nextFilter'
	scripts/vscripts/libraries\containers.lua:675: in function <scripts/vscripts/libraries\containers.lua:668>

**Comment by Trildar** [comment]
Not necessary for fixing, but I'm curious, is there at least one consistent action that produces this? I'm wondering under what circumstances the target would be nil.

**Comment by chrisinajar** [comment]
bots make it spam this error, not sure how to cause it with humans

**Comment by RamonNZ** [comment]
Oh you're right, I just realized that it would be a weird combination of bot behavior and the rules. I'm pretty sure a bot just tried to sell a clarity. I'll stop them doing that.

**Comment by Trildar** [comment]
Yeah, a check for nil target can be added. I just find it a little odd that it would be nil since I also tested player selling by doing right click > sell, which gives a target entity index of 0 which apparently doesn't return a nil when you try to pass it to `EntIndexToHScript`. I'm guessing bots give -1 in some of their orders or something.
