### ISSUE TITLE
Implement arena shops

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#511]
Place a shop at each duel arena's smaller raised platform, which sells sentries and dust (make it the side shop internally)

**Comment by darklordabc** [comment]
Seems unnecessary, players know when a duel is about to come, they have plenty of time to buy sentries and dusts beforehand.

**Comment by KarmaticNeutral** [comment]
That is the map design. The small high ground in the middle is an intended shop that only sells wards and other types of detection

**Comment by Haganeko** [comment]
It is why the platforms exist in the first place. We wish to avoid invisible heroes just running the clock out.

**Comment by darklordabc** [comment]
But players will know if they are vsing invisible heroes at the beginning of most duels. Also, there is simpler ways to remove invisibility for duels, just apply dust to all heros.

**Comment by KarmaticNeutral** [comment]
Then that completely makes invis unusable in duels. That's not what we want. And we have to acocunt for the fact that some of our players are very bad at the game and assume they don't prepare. It's better to put in the shop than to make both teams sit and wait for 2 minutes every duel because a riki is on the other team and this team is stupid.

**Comment by darklordabc** [comment]
In Redux for duels, we made it so that if a hero on the enemy team had not been seen in 7 seconds, both teams were revealed. That would work here. I just think creating a shop in a duel areana is not a natural thing to see in an arena, and seems a complicated solution to a simple problem, thats my 5c.

**Comment by KarmaticNeutral** [comment]
Alternative solution is that after holding the command zone, one of the buffs is true sight. This way if a invis hero tries to run, you just go to the command point until you get true sight. If they try to contest, you'll be able to tell where they are without seeing them, if they don't, you'll be able to see them. (or you can just bring dust/sents to the arena by being prepared)

**Comment by l34Um1** [comment]
we are doing the shop

**Comment by warpdragon** [comment]
Ooh this could be fun

**Comment by warpdragon** [comment]
Boom. https://moddota.com/forums/discussion/4/datadriven-items##shops.
Droppin bombs up in this bitch.
