### ISSUE TITLE
Integrate custom gold system with shop and buyback

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#55]
Currently the custom gold system doesn't work with any of the built in dota stuff.

* [x] Make buying from shop use custom gold
* [x] Make buyback use custom gold
  * [ ] UI elements which show if buyback is available (plus tooltips)

**Comment by Chronophylos** [comment]
[ ] Make bounties use custom gold

**Comment by chrisinajar** [comment]
Well, doesn't anything that currently *gives* gold fine, since the system will automatically think it out of your gold stash? The only important ones initially are stuff that spends, since that's all entirely broken... or did i miss a thing?

**Comment by Chronophylos** [comment]
Yes, adding gold, like selling or bounties is fine.
I'm just trying to get everything together that needs a change.

**Comment by Rachol** [comment]
I think you pretty much need to create entirely new shop to allow for the new gold system to work for buying and selling items.

However... if you agree to cap the item prices to some reasonable level, lets say max 50000 gold. Then you can pull up an easy workaround.

Modify the current implementation of the custom gold, so that it doesn't keep dota gold at 0, but keeps the dota gold between 0 and 50000. This way, you can make all the shop purchases work as normal.

Please note that in this kind of system purchasing items that cost more than 50000 is impossible if they can't be combined from other items... If they do combine, it is still not possible to buy it directly, but you must by the "parts" first until the "gold to complete" is lower than 50000.

Of course, you could make the limit higher. Let's say 80000 or 90000 for example... It pretty much depends on how much "dota bounty" you get from regular dota events (player kills for example).

**Comment by Rachol** [comment]
If you think that the above solution is good enough, I can do it.

**Comment by Chronophylos** [comment]
For now it's fine so go ahead.

**Comment by chrisinajar** [comment]
current solutions work enough, we'll create granular tickets for the minute interactions
