### ISSUE TITLE
Simple Bosses #6: Jingu Mastery

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#870]
This is just a bunch of simple bosses. These just have basic Dota abilities added into their toolset to make them slightly more interesting than a regular DPS race.

Please expose all the expected values in the KV (dmg, attack speed, armor etc) as well as values from the bosses abilities so they can be edited and adjusted.

This boss uses Monkey Kings passive Jingu Mastery.

**Comment by Minnakht** [comment]
Balance deputy request: Both Base Attack Time and some baseline attack speed bonus here would be really nice if they were exposed, and also initially declared with the idea of making the boss attack pretty slow. 

Due to lifesteal being very effective when bosses use it, due to boss resistance, the optimal strategy here is to never let the boss actually count up to four Jingu hits, and thus that would need to be appropriately possible. 

This is, of course, the balance team's problem in the end, but I want to make this note of it to help create a good initial state for us to work from.

**Comment by Trildar** [comment]
Base Attack Time is inherently available in KV for any unit definition. The Attack Speed will probably require some generic Boss Attack Speed ability.

**Comment by l34Um1** [comment]
Don't worry about attack speed since we can just use the BAT for it.

**Comment by Trildar** [comment]
Adjusting both allows control of how the boss is affected by -attack speed though.

**Comment by imaGecko** [comment]
No attack speed means the boss is trivialized by shivas. No need for even another attack speed slowing ability

**Comment by warpdragon** [comment]
combined with #865
