### ISSUE TITLE
Simple Bosses #8: Reactive Armor

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#872]
This is just a bunch of simple bosses. These just have basic Dota abilities added into their toolset to make them slightly more interesting than a regular DPS race.

Please expose all the expected values in the KV (dmg, attack speed, armor etc) as well as values from the bosses abilities so they can be edited and adjusted.

This boss uses Timbersaws passive Reactive Armor.

This boss is supposed to have low HP, no magic resistance and high physical armor. A boss that casters excel at killing.

**Comment by Minnakht** [comment]
Balance deputy note: Due to armor and the hp regen granted by Reactive Armor, there will be a calculable point where physical attacks with insufficient damage will end up dealing so little damage it'll be completely balanced by the regen. We should keep track of this number as it will be important for balancing this boss.

@Haganeko hey there's math for you to eat, are you hyped

**Comment by KarmaticNeutral** [comment]
If we just utilize the vanilla version of this spell, silver edge works on it. I think this should be done. With the bosses inherent duration reduction, this would make for an amazing communication point.

**Comment by Minnakht** [comment]
It'd only prevent new stacks from being added for as long as it lasts, so... yeah, pretty fair point, honestly.

Some initial mathhammer: assuming reactive armor grants 32 armor at max stacks and can heal about 30 hp over a stack's duration, and assuming the boss has 25 armor (and it will have more than that), at full stacks the boss has ~60 armor for ~78% physical damage reduction, which together with 85% boss resistance means... if your hits deal less than 900 damage base, it'll be reduced to below 30 by boss resistance and armor, and thus the boss will heal the hit back.

At 25 armor and no armor stacks, that value is 500. 

A possible design decision would be to tweak the reactive armor so that its duration is halved and its regen is made twice as high. There are reasons why I think that'd be good, namely making it more forgiving if someone attacks by accident and also letting more stacks be "buffered in" should people try to overload the boss by constantly hitting past the stack cap.

Eh, all the considerations could be saved for when the boss is out. We'll see how it plays.

**Comment by KarmaticNeutral** [comment]
I would say the easier solution is don't give the boss base armor.

**Comment by KarmaticNeutral** [comment]
or significantly less

**Comment by Minnakht** [comment]
It contradicts the initial design idea, which is of a boss which is infeasible to kill with physical damage anyway and weak to magic instead, though. 25 base armor is the standard and I think it could provide a fair enough result for players to fight against - if someone can deal 500 physical in one hit, they're welcome to squeeze the occassional hit in, anyone else should stick to spells, that's the intended strats and that's probably fine.

Once again, we'll see how it plays. If it doesn't play well, then the base armor can be lowered below 25 to drop the worthwhile damage threshold from 500 to something more reasonable for when people take t1.5 bosses. For now we have zero idea, just concepts of numbers.

**Comment by warpdragon** [comment]
Honestly I'm not sure I even like this. The point of reactive armor on timber is to encourage him to be aggressive in lane using an interesting survivability mechanic that players are rewarded for using intelligently. Does it even make sense to give a boss reactive armor when you could simply give him passive armor/regen?

**Comment by Minnakht** [comment]
Also note the stacks heal over 19 seconds. When the boss is low on HP, and could be killed in like 7 seconds if attack damage was added in so only about 1/3 of the stack healing has to be accounted for, then the damage threshold drops to like 300 (because then we're looking at the stacked-up one again.)

**Comment by Minnakht** [comment]
I don't think it makes sense to give a boss passive regen, because then we could just estimate a "reasonable kill time" for the boss (with an upper bound of 120 seconds) and then give the boss thatmany*regenvalue HP and it'd be strictly better since it'd do more even if the boss was killed faster than expected. Similarly, passive armor could be just included in the base armor value.

Reactive armor has potential for emergent gameplay, and I'm curious to see it explored. At worst it'll turn out to be a bad idea and we'll scrap what'll likely end up being literally minutes of @Chronophylos 's work.

**Comment by warpdragon** [comment]
they're all getting scrapped. it better have a kickass armor animation or else its complete garbage.

**Comment by warpdragon** [comment]
lol wrong button

**Comment by warpdragon** [comment]
From Dota 2 Wiki: "The amount of stacks is also visually indicated by a dome which closes over on Timbersaw:

    1–4 stacks: 1st fragment of the dome appears
    5–8 stacks: 2nd fragment of the dome appears
    9–13 stacks: 3rd fragment of the dome appears
    14–16 stacks: 4th fragment of the dome appears (it is now fully closed)
    17–20 stacks: fire comes out of the suit's chimney"

**Comment by Minnakht** [comment]
https://i.gyazo.com/f8271a56c7a4eccd3313b60f55c4826a.png

**Comment by warpdragon** [comment]
as long as it looks "super cool"

**Comment by Minnakht** [comment]
worry not, we have a real good artist on the job

**Comment by warpdragon** [comment]
combined with #865
